#
# Eduardo Stuani Solution(s) for Project Euler Problem Number 2
# https://github.com/stuaninauts
#
# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not exceed four million,
# find the sum of the even-valued terms.


# Solution 1
def solve():
    numbers = [1, 2]
    total = 0

    for i in range(4000000):
        if i == numbers[-1] + numbers[-2]:
            numbers.append(numbers[-1] + numbers[-2])

    for k in numbers:
        if k % 2 == 0:
            total += k

    return total


if __name__ == "__main__":
    print(solve())
